### ISSUE TITLE
[bug] Pieconomy's not registering an economy provider.

### ISSUE THREAD

**Issue by GazbonicAcid** [pie-flavor/Pieconomy#1]
Running
Sponge Forge: spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar
Pieconomy: Pieconomy-0.1.0.jar
Mods: see [Planetary Alignment](https://www.atlauncher.com/packs/RuneFestival/) \(name change pending\)
Here's the [ATLauncher Console Log](http://paste.atlauncher.com/view/406acb70) if that helps.
[pieconomy.conf](https://hastebin.com/quwecazoka.conf)
[CustomNPCs-latest.log](https://hastebin.com/jenewozenu.log)
[fml-junk-earlystartup.log](https://hastebin.com/ugoxahodeg.log)
[latest.log](https://hastebin.com/karibayeyo.log)
[fml-server-latest.log](https://github.com/pie-flavor/Pieconomy/files/1129047/fml-server-latest.log.txt)
[Backup upload of fml-server-latest.log](https://filebin.net/9x38ihkwii5vrk8k/fml-server-latest.log)

**Comment by pie-flavor** [comment]
Lines 5029-5090:
```
[14:25:31] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=pieconomy, name=Pieconomy, version=0.1.0, description=An economy plugin that uses items as currency, authors=[pie_flavor], source=/home/mch/multicraft/servers/server38373/./plugs/plugins/Pieconomy-0.1.0.jar}
java.io.IOException: configurate.typesafe.config.ConfigException$Parse: Reader: 33: Expecting a value but got wrong token: ',' ('$' not followed by {, ',' not allowed after '$') (if you intended ',' ('$' not followed by {, ',' not allowed after '$') to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:171) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:42) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at flavor.pie.pieconomy.Pieconomy.preInit(Pieconomy.kt:51) ~[Pieconomy.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Pieconomy_preInit8.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:216) [SpongeMod.class:1.11.2-2315-6.1.0-BETA-2434]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:561) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: configurate.typesafe.config.ConfigException$Parse: Reader: 33: Expecting a value but got wrong token: ',' ('$' not followed by {, ',' not allowed after '$') (if you intended ',' ('$' not followed by {, ',' not allowed after '$') to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:422) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.consolidateValues(ConfigDocumentParser.java:152) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:420) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:405) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:405) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:595) ~[ConfigDocumentParser$ParseContext.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14) ~[ConfigDocumentParser.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260) ~[Parseable.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248) ~[Parseable.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:180) ~[Parseable.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:174) ~[Parseable.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.impl.Parseable.parse(Parseable.java:299) ~[Parseable.class:1.11.2-2315-6.1.0-BETA-2434]
	at configurate.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:668) ~[ConfigFactory.class:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:104) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:54) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:163) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	... 35 more
```

A raw `$` is not a valid Configurate value, since $ is used for references. Add quotes to the currency symbol.

**Comment by GazbonicAcid** [comment]
Take-off pebkac, still throwing the error after surrounding it with quotes.
Tried both single \' and double \" too.
[Logs.zip](https://github.com/pie-flavor/Pieconomy/files/1129919/Logs.zip)
@pie-flavor

**Comment by pie-flavor** [comment]
Nope.
Lines 5029-5073:
```
[22:27:53] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=pieconomy, name=Pieconomy, version=0.1.0, description=An economy plugin that uses items as currency, authors=[pie_flavor], source=/home/mch/multicraft/servers/server38373/./plugs/plugins/Pieconomy-0.1.0.jar}
ninja.leaping.configurate.objectmapping.ObjectMappingException: Input 'modcurrency:banknote:0' was not a valid value for type org.spongepowered.api.item.ItemType
	at org.spongepowered.common.config.CatalogTypeTypeSerializer.deserialize(CatalogTypeTypeSerializer.java:45) ~[CatalogTypeTypeSerializer.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.common.config.CatalogTypeTypeSerializer.deserialize(CatalogTypeTypeSerializer.java:39) ~[CatalogTypeTypeSerializer.class:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$MapSerializer.deserialize(TypeSerializers.java:165) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$MapSerializer.deserialize(TypeSerializers.java:143) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:85) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.deserialize(TypeSerializers.java:256) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:226) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:356) ~[spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar:1.11.2-2315-6.1.0-BETA-2434]
	at flavor.pie.pieconomy.Pieconomy.preInit(Pieconomy.kt:51) ~[Pieconomy.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Pieconomy_preInit8.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.11.2-2315-6.1.0-BETA-2434]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:216) [SpongeMod.class:1.11.2-2315-6.1.0-BETA-2434]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:561) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
Seriously, _check the log_. I just pushed Ctrl F, searched 'economy', and hit enter until a stack trace appeared.
In Java, that section is mapped by `ItemType`. As in `modcurrency:banknote`. That is an item type ID. I should add a way to use a data value, but right now there isn't one. But nowhere in Minecraft is `<id>:<data value>` a standard notation.
