### ISSUE TITLE
could not perform config operations

### ISSUE THREAD

**Issue by Stuperfied** [pie-flavor/Pieconomy#1]
Sponge server under Windows 10 64bit
[11:16:12 INFO]: SpongeVanilla
    Minecraft: 1.11.2
    SpongeAPI: 6.0.0-SNAPSHOT-1822f21
    SpongeVanilla: 1.11.2-6.0.0-BETA-220

[11:08:49 INFO] [Sponge]: Loaded plugin: Pieconomy 1.1.0 (from mods\Pieconomy-1.1.0.jar)
[11:08:49 INFO] [Sponge]: Loaded plugin: Nucleus 0.23.2-S5.1 (from mods\Nucleus-0.23.2-1.10.2-S5.1-plugin.jar)
[11:08:49 INFO] [Sponge]: Initializing plugins...
[11:08:49 ERROR] [pieconomy]: Could not perform config operations! Disabling.
[11:08:49 ERROR] [STDERR]: java.io.IOException: The system cannot find the path specified
[11:08:49 ERROR] [STDERR]:      at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[11:08:49 ERROR] [STDERR]:      at java.io.File.createNewFile(Unknown Source)
[11:08:49 ERROR] [STDERR]:      at flavor.pie.Pieconomy.onPreInit(Pieconomy.java:63)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Pieconomy_onPreInit5.handle(Unknown Source)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:324)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:199)
[11:08:49 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:110)
[11:08:49 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$znn000(SourceFile:1223)
[11:08:49 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:112)
[11:08:49 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:436)
[11:08:49 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)

**Comment by pie-flavor** [comment]
Mayhaps you missed the memo. This is not a functional plugin.
