### ISSUE TITLE
Error after changing default config

### ISSUE THREAD

**Issue by Ve6om** [pie-flavor/Pieconomy#17]
**ERROR:**

> [23:22:49] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task pieconomy-S-39 owned by Plugin{id=pieconomy, name=Pieconomy, version=0.6.2, description=An economy plugin that uses items as currency., authors=[pie_flavor], source=/home/container/./mods/plugins/Pieconomy-0.6.2.jar}, but an error occured.
flavor.pie.pieconomy.runtime.kotlin.UninitializedPropertyAccessException: lateinit property channel has not been initialized
at flavor.pie.pieconomy.Pieconomy.getChannel(Pieconomy.kt:56) ~[Pieconomy.class:?]
at flavor.pie.pieconomy.Pieconomy$join$$inlined$Task$lambda$1.accept(Pieconomy.kt:198) ~[Pieconomy$join$$inlined$Task$lambda$1.class:?]
at flavor.pie.pieconomy.Pieconomy$join$$inlined$Task$lambda$1.accept(Pieconomy.kt:39) ~[Pieconomy$join$$inlined$Task$lambda$1.class:?]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.7]
at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.1.7]
at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.1.7]
at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.1.7]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_212]
at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7]
at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7]
at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.1.7]
at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:458) [SpongeMod.class:1.12.2-2838-7.1.7]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**CONFIG:**

items {
  "minecraft:prismarineshard" {
    currency = shard
    amount = 1
  }
}

currencies {
  shard {
    decimal-places = 0
    name = {text = Apollo Shard}
    plural = {text = Apollo Shards}
    symbol = {text = AS, color = aqua}
    format = {text = "%{amount}% %{symbol}%"}
    exchangeable = false
  }
}

default-currency = shard

server-accounts {
  enable = true
  autosave-interval = 20
  accounts = [
    {
      id = "bank"
      name = "Bank"
      currencies {
        values = []
        type = blacklist
      }
      negative-values {
        values = []
        type = whitelist
      }
    }
  ]
  dynamic-accounts {
    enable = false
    currencies {
      values = []
      type = blacklist
    }
    negative-values {
      values = []
      type = whitelist
    }
  }
}

version = 3

**Comment by Ve6om** [comment]
[config.txt](https://github.com/pie-flavor/Pieconomy/files/4242704/config.txt)
[error.txt](https://github.com/pie-flavor/Pieconomy/files/4242705/error.txt)

**Comment by Ve6om** [comment]
Item name was incorrect.
minecraft:prismarine_shard
