### ISSUE TITLE
ERROR [1.12]

### ISSUE THREAD

**Issue by TooVeryIcey** [pie-flavor/Pieconomy#4]
[20:43:19 ERROR] [Sponge]: Could not pass GameInitializationEvent$Impl to Plugin{id=pieconomy, name=Pieconomy, version=0.3.0, description=An economy plugin that uses items as currency, authors=[pie_flavor], source=mods/Pieconomy-0.3.0.jar}
java.io.EOFException: null
	at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_131]
	at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_131]
	at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_131]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(SourceFile:114) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(SourceFile:84) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(SourceFile:80) ~[gi.class:?]
	at org.spongepowered.common.data.persistence.NbtDataFormat.readFrom(NbtDataFormat.java:57) ~[NbtDataFormat.class:1.12-7.0.0-BETA-306]
	at flavor.pie.pieconomy.Pieconomy.init(Pieconomy.kt:97) ~[Pieconomy.class:?]
	at org.spongepowered.common.event.listener.GameInitializationEventListener_Pieconomy_init24.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12-7.0.0-BETA-306]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:349) [SpongeEventManager.class:1.12-7.0.0-BETA-306]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:366) [SpongeEventManager.class:1.12-7.0.0-BETA-306]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:370) [SpongeEventManager.class:1.12-7.0.0-BETA-306]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:205) [SpongeImpl.class:1.12-7.0.0-BETA-306]
	at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:153) [SpongeVanilla.class:1.12-7.0.0-BETA-306]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zok000(SourceFile:1237) [nx.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:188) [nx.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by pie-flavor** [comment]
Can you please attempt to open your `server_accounts.dat` file with an NBT editor? If it fails, then it has almost definitely been corrupted, and needs to be deleted or renamed.

**Comment by TooVeryIcey** [comment]
Thanks! that seemed to fix it
